package com.example.sqlworm;


import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Color;
import android.os.Bundle;

import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.text.Layout;
import android.text.Spannable;
import android.text.SpannableString;
import android.text.style.AlignmentSpan;
import android.util.Log;
import android.view.Gravity;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.view.Window;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;
import android.view.inputmethod.EditorInfo;
import android.widget.TextView;
import android.view.KeyEvent;

import org.w3c.dom.Text;

public class data extends MainActivity {

    public void chez() {


        SQLiteDatabase mydatabase = getBaseContext().openOrCreateDatabase("mydatabase5.db", MODE_PRIVATE, null);
        String mystring1 = "DROP TABLE IF EXISTS rmtable;";
        mydatabase.execSQL(mystring1);
        mystring1 ="CREATE TABLE IF NOT EXISTS rmtable(postcode TEXT, street TEXT, round TEXT);";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AA','Thornwell Road', 'T1');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AB', 'Mathern Way','T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AD','Cromwell Road', 'T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AE', 'St. Ewans Road','T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AF', 'Pembroke Road','T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AG', 'Channel View','T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AH', 'Channel View','T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AJ', 'Channel View','T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AL', 'Queens Road', 'T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AN', 'Queens Road','T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AP', 'Brunel Road','T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AQ', 'Striguil Road','T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AR','Burnt Barn Road', 'T1');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AS', 'Western Ave','T5');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AU', 'Meadow Walk','T12');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES('NP165AW', 'Mounton Road Meadow Lane', 'T12');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES('NP165AX','River View',  'T18');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AY','Tempest Drive', 'T12');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165AZ','Penterry Park', 'T12');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BA', 'Newport Road','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BB', 'Newport Road','R2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BD', 'Beech Grove','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BE', 'Beech Grove','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BG', 'High Beech Lane','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BH', 'Larkfield Avenue','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BJ', 'St. Lawrence Road','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BL', 'Mounton Road','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BP', 'Ruffets Close','T12');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BQ', 'High Beech Lane','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BR', 'Mounton Road','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BS', 'Mounton Road','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BT', 'Newport Road','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BU', 'Warwick Close','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BW', 'The Paddocks','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BW', 'Fair View','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165BY', 'Regent Way, Mounton Road','T12');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES('NP165BZ', 'School Hill', 'T1');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES('NP165DA', 'Albion Square', 'T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DB', 'Moor Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DD', 'Moor Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DE', 'Moor Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DF', 'Moor Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DG', 'Hardwick Terrace','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DH', 'Thomas Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DJ', 'Hardwick Avenue','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DL', 'Portwall Road','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DN', 'Green Street','R1');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DP', 'Green Street','R1');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DQ', 'Wye Crescent','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DR', 'Unknown Hardwick','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DS', 'Hardwick Avenue','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DT', 'Rockwood Road','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DU', 'Unknown Hardwick','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DW', 'Wye Crescent','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DX', 'Caird Street','T9');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DY', 'Hughes Crescent','T15');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165DZ', 'Severn Crescent','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EA', 'Severn Crescent','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EB', 'Hardwick Avennue','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165ED', 'Garden City Way','T18');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EE', 'Waters Road','R10');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EF', 'Garden City Way','T18');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EG', 'Mounton Close','T12');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EH', 'Mounton Drive','T12');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EJ', 'Riflemans Way','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EL', 'Bank Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EN', 'Bank Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EP', 'Beaufort Square','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EQ', 'Davis Court','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165ER', 'Hocker Hill Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165ES', 'Bridge Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165ET', 'Middle Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EU', 'St. Mary Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EW', 'St. Mary Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EX', 'Upper Church Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EY', 'Bridge Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165EZ', 'Bridge Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165FA', 'The Headland','T20');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165FB', 'Badgers Dene','T12');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165FD', 'St. Lawrence Close','T2');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165FE', 'Bank Street','T4');";
        mydatabase.execSQL(mystring1);
        mystring1 ="INSERT INTO rmtable VALUES( 'NP165FY', 'The Back','T4');";
        mydatabase.execSQL(mystring1);


    }

}
